Namespace Enums
    <Serializable()> Public Enum Entity
        [NOTHING]

        ACCESSORY
        ACCESSORYCATEGORY
        ACCESSORYGENERATION
        BODY
        CAR
        CARACCESSORY
        CARPART
        CLASSIFICATION
        ENGINE
        ENGINECATEGORY
        EQUIPMENT
        EQUIPMENTCATEGORY
        EQUIPMENTFITTING
        EQUIPMENTGROUP
        EXTERIORCOLOUR
        EXTERIORCOLOURTYPE
        FACTORYCAR
        FACTORYGRADE
        FUELTYPE
        GRADE 'TODO: remove this one (promotions translations are defined on entity of promotion (which can be this GRADE), not on 'promotion' entity => when this is solved, GRADE member can be removed again)
        INTERIORCOLOUR
        MODEL
        MODELGENERATION
        PACK
        STEERING
        TECHSPEC
        TECHSPECCATEGORY
        TRANSMISSION
        TRANSMISSIONTYPE
        TRIMMING
        UPHOLSTERY
        UPHOLSTERYTYPE
        CARCOLOURCOMBINATION
        CAREQUIPMENT
        CAREXTERIORCOLOUR
        CARPACK
        CARTECHSPEC
        CARUPHOLSTERY
        MODELGENERATIONBODY
        MODELGENERATIONWHEELDRIVE
        MODELGENERATIONENGINE
        FACTORYGENERATIONOPTIONVALUE
        MODELGENERATIONGRADE
        MODELGENERATIONGRADECLASSIFICATION
        MODELGENERATIONGRADESUBMODEL
        MODELGENERATIONTECHSPEC
        MODELGENERATIONTRANSMISSION
        MODELSUBSET
        PACKEQUIPMENT
        PROMOTION
        WHEELDRIVE
        SUBMODEL
        UNIT
        FILTERVALUE

    End Enum
End NameSpace